import { CoreMessage, LanguageModel, streamText } from 'ai';
import { getModel } from '../utils';
import { LocationResponse } from '@/lib/types/map-schemas';

// Simplified prompt for reliable GeoJSON and command extraction
const GEOJSON_ENRICHMENT_PROMPT = `
You are an AI assistant specializing in geospatial data extraction.
Your task is to process a given text and extract the following information:

1.  "text": The original textual response that should be displayed to the user.
2.  "geojson": A valid GeoJSON FeatureCollection representing any locations, addresses, coordinates, or routes mentioned in the text.
3.  "map_commands": A list of map camera commands to control the map view, such as flying to a location.

Rules for GeoJSON:
- Convert all found locations into appropriate GeoJSON features (Point, LineString, Polygon).
- Use the correct coordinate format: [Longitude, Latitude] in WGS84.
- Include meaningful properties for each feature (e.g., "name", "description").
- If no geographic data can be extracted, set "geojson" to null.

Rules for Map Commands:
- Identify actions in the text that imply map movements (e.g., "fly to," "center on," "zoom to").
- Create a list of command objects with these formats:
  - flyTo: { "command": "flyTo", "params": { "center": [lon, lat], "zoom": 15 } }
  - fitBounds: { "command": "fitBounds", "params": { "bounds": [[west, south], [east, north]] } }
  - setCenter: { "command": "setCenter", "params": { "center": [lon, lat] } }
  - setZoom: { "command": "setZoom", "params": { "zoom": 12 } }
- If multiple locations are mentioned, use fitBounds to show them all.
- If a single location is mentioned, use flyTo with appropriate zoom.
- If no map commands can be inferred, set "map_commands" to null.

The final output MUST be a single JSON object that strictly follows the LocationResponse interface.
Return ONLY the raw JSON object with no surrounding markdown, code fences, or any additional text or explanation.

Here is the text to process:
`;

/**
 * Enhanced GeoJSON Enricher using simplified reliable approach
 * This version prioritizes reliability over complexity
 * 
 * @param researcherResponse The text generated by the researcher agent
 * @param mcpClient Optional MCP client for enhanced geocoding and map operations
 * @returns A promise that resolves to a LocationResponse object
 */
export async function geojsonEnricherV2(
  researcherResponse: string,
  mcpClient?: any
): Promise<LocationResponse> {
  const model = (await getModel()) as LanguageModel;
  const messages: CoreMessage[] = [
    {
      role: 'user',
      content: `${GEOJSON_ENRICHMENT_PROMPT}\n\n${researcherResponse}`,
    },
  ];

  try {
    console.log('🚀 Starting enhanced GeoJSON enrichment...');
    console.log('📝 Input text:', researcherResponse.substring(0, 200) + '...');
    
    const { text } = await streamText({
      model,
      messages,
      maxTokens: 2048,
    });

    // Assuming the LLM returns a valid JSON string, parse it.
    let responseText = await text;
    console.log('📄 Raw LLM response:', responseText.substring(0, 500));

    // Strip markdown code fences if present
    const jsonMatch = responseText.match(/```(json)?\n([\s\S]*?)\n```/);
    if (jsonMatch && jsonMatch[2]) {
      responseText = jsonMatch[2].trim();
      console.log('✂️ Stripped markdown fences');
    }

    const enrichedData = JSON.parse(responseText) as LocationResponse;
    
    console.log('✅ Enhanced GeoJSON enrichment complete:', {
      hasGeoJSON: !!enrichedData.geojson,
      featureCount: enrichedData.geojson?.features?.length || 0,
      hasCommands: !!enrichedData.map_commands,
      commandCount: enrichedData.map_commands?.length || 0,
      commands: enrichedData.map_commands?.map(c => c.command),
    });

    return enrichedData;
  } catch (error) {
    console.error('❌ Enhanced GeoJSON enrichment error:', error);
    
    // Fallback to basic response
    return {
      text: researcherResponse,
      geojson: null,
      map_commands: null,
    };
  }
}

/**
 * Backward compatibility wrapper
 * Maintains the same interface as the original geojsonEnricher
 */
export async function geojsonEnricher(
  researcherResponse: string
): Promise<LocationResponse> {
  return geojsonEnricherV2(researcherResponse);
}
