import { mapControlOrchestrator } from './map-control-orchestrator';
import { LocationResponse } from '@/lib/types/map-schemas';

/**
 * Enhanced GeoJSON Enricher using Multi-Agent Orchestrator
 * This replaces the simple geojsonEnricher with a sophisticated multi-agent system
 * 
 * @param researcherResponse The text generated by the researcher agent
 * @param mcpClient Optional MCP client for enhanced geocoding and map operations
 * @returns A promise that resolves to a LocationResponse object
 */
export async function geojsonEnricherV2(
  researcherResponse: string,
  mcpClient?: any
): Promise<LocationResponse> {
  try {
    console.log('🚀 Starting enhanced GeoJSON enrichment with multi-agent orchestrator...');
    
    const response = await mapControlOrchestrator(researcherResponse, {
      maxIterations: 3,
      enableFeedbackLoop: true,
      mcpClient: mcpClient || null,
    });

    console.log('✅ Enhanced GeoJSON enrichment complete:', {
      hasGeoJSON: !!response.geojson,
      commandCount: response.map_commands?.length || 0,
      confidence: response.metadata?.confidence,
      processingTime: response.metadata?.processingTime,
    });

    return response;
  } catch (error) {
    console.error('❌ Enhanced GeoJSON enrichment error:', error);
    
    // Fallback to basic response
    return {
      text: researcherResponse,
      geojson: null,
      map_commands: null,
      metadata: {
        confidence: 0,
        processingTime: 0,
        mcpQueriesUsed: [],
        iterationCount: 0,
      },
    };
  }
}

/**
 * Backward compatibility wrapper
 * Maintains the same interface as the original geojsonEnricher
 */
export async function geojsonEnricher(
  researcherResponse: string
): Promise<LocationResponse> {
  return geojsonEnricherV2(researcherResponse);
}
